### ISSUE TITLE
doesnt work when work is different drive than cache

### ISSUE THREAD

**Issue by davhdavh** [MasterworksIO/action-local-cache#15]
I tried the demo that is in .github, but keep getting errors

```
EXDEV: cross-device link not permitted, rename '/home/runner/_work/b/b/demo-output.txt' -> '/home/runner/_work/_tool/c/b/CACHE_V1-5855140606-4/demo-output.txt'
```

**Comment by stefanmaric** [comment]
Hi @davhdavh,

This action uses renaming as a means to make cache reads and writes as fast as possible, that of course doesn't work across drives.

We might add a copy strategy fallback when we get the chance.

**Comment by zulman** [comment]
Hello all,

+1 to the adding copy strategy fallback. 

Thanks!

**Comment by oNaiPs** [comment]
My suggestion would be to support different cache moving/copying strategies, on top of my head i can remember:
- Move - moves cache files (current implementation). One current drawback is that if the build fails, the post action is not run (is this fixable?)
- Soft/Hard Link - would have to test but could be useful for some use cases?
- Copy - does `cp -rf`, allows creating immutable caches.
- Compress - Like Copy, but compresses to a single file. Not sure about usefulness.
- Rsync - use rsync to have the cache and the target dirs in sync (faster than Copy)

I'd be willing to start implementation on this. My home lab is set up with docker instances and the current strategy fails since the tool directory is a volume mount. Would you accept a PR for this feature?

Thanks!
